config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get '/projects/:project_id/phases/:phase_id/sprints/:id/start_sprint' => 'sprints#start_sprint', as: :sprint_start
  get '/projects/:project_id/phases/:phase_id/sprints/:id/end_sprint' => 'sprints#end_sprint', as: :sprint_end

  resources :projects do
    resources :team_members
    resources :teams
    resources :phases do
      resources :experiments
      resources :sprints
    end
  end

  root 'projects#index'

  post 'send_weekly_emails' => 'projects#send_weekly_emails', as: :email_sent

end

app/models/sprint.rb
class Sprint < ApplicationRecord
  belongs_to :phase
  has_and_belongs_to_many :experiments

  accepts_nested_attributes_for :experiments, allow_destroy: true, :reject_if => :all_blank

  before_save :default_values

  def default_values
    self.completed ||= false
  end

end

app/controllers/sprints_controller.rb
class SprintsController < ApplicationController
  before_action :set_project, only: [:index, :show, :new, :edit, :create, :start_sprint, :end_sprint, :update, :destroy]
  before_action :set_phase, only: [:index, :show, :new, :edit, :create, :start_sprint, :end_sprint, :update, :destroy]
  before_action :set_sprint, only: [:show, :edit, :start_sprint, :end_sprint  , :update, :destroy]

  # GET /sprints
  # GET /sprints.json
  def index
    @sprints = Sprint.where(phase_id: params[:phase_id])
  end

  # GET /sprints/1
  # GET /sprints/1.json
  def show
  end

  # GET /sprints/new
  def new
    @sprint = Sprint.new
  end

  # GET /sprints/1/edit
  def edit
  end

  # POST /sprints
  # POST /sprints.json
  def create
    @sprint = Sprint.new(sprint_params)

    respond_to do |format|
      if @sprint.save
        format.html { redirect_to project_phase_path(@project.id, @phase.id), notice: 'Sprint was successfully created.' }
        format.json { render :show, status: :created, location: @sprint }
      else
        format.html { render :new }
        format.json { render json: @sprint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sprints/1
  # PATCH/PUT /sprints/1.json
  def update
    respond_to do |format|
      if @sprint.update(sprint_params)
        format.html { redirect_to project_phase_path(@project.id, @phase.id), notice: 'Sprint was successfully updated.' }
        format.json { render :show, status: :ok, location: @sprint }
      else
        format.html { render :edit }
        format.json { render json: @sprint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sprints/1
  # DELETE /sprints/1.json
  def destroy
    @sprint.destroy
    respond_to do |format|
      format.html { redirect_to project_phase_sprint_path(@project.id, @phase.id), notice: 'Sprint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def start_sprint
  end

  def end_sprint
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:project_id])
    end
    def set_phase
      @phase = Phase.find(params[:phase_id])
    end
    def set_sprint
      @sprint = Sprint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sprint_params
      params.require(:sprint).permit(:name, :start_date, :end_date, :completed, :project_id, :phase_id, :est_points, :things_done, :things_learned, :act_points, :impediment, :retro_actions, :avg_happy, :on_target, :organization_helping, :able_to_pull_of, :impediment, experiment_ids:[], experiments_attributes: [:id, :act_succes_metric_1, :act_succes_metric_2, :act_succes_metric_3, :act_succes_metric_4, :act_succes_metric_5])
    end
end

app/helpers/sprints_helper.rb
module SprintsHelper
end

app/views/sprints/_begin_form.html.erb
<p><b>Project:</b> <em><%= @project.name %></em> - <b>Phase:</b> <em><%= @phase.name %></em></p>
<%= form_for([@project, @phase, @sprint]) do |f| %>
  <% if @sprint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sprint.errors.count, "error") %> prohibited this sprint from being saved:</h2>

      <ul>
      <% @sprint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="phase_table">
    <% @phase.experiments.each do |exp| %>
    <tr>
      <td><%= exp.name %></td>
      <td>
        <% if  !exp.completed %>
          <span class="glyphicon glyphicon-check boxes"></span>
        <% else %>
          <span class="glyphicon glyphicon-unchecked boxes"></span>
        <% end %>
      </td>
      <td> <%= link_to "Update experiment", edit_project_phase_experiment_path(@project.id,@phase.id,exp.id), :class => 'btn btn-active' %> </td>
    </tr>
    <% end %>
  </table>

  <div class="field">
    <%= f.label "Select the relevant experiments for this sprint:" %>
    <%= f.collection_check_boxes :experiment_ids, @phase.experiments.all, :id, :name do |b| %>
    <div class="collection-check-box">
      <%= b.check_box %>
      <%= b.label %>
    </div>
    <% end %>
  </div>

  <%= link_to "Create a new experiment", new_project_phase_experiment_path(@project.id,@phase.id), :class => 'btn btn-active' %>

  <div class="field form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :start_date %>
    <%= f.date_select :start_date, { ampm: true, order: [:day, :month, :year] }, { class: "form-control" } %>
  </div>

  <div class="field form-group">
    <%= f.label :end_date %>
    <%= f.date_select :end_date, { ampm: true, order: [:day, :month, :year] }, { class: "form-control" } %>
  </div>

  <div class="field form-group">
    <%= f.label 'Estimated sprint points' %>
    <%= f.number_field :est_points, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label 'Average happy score' %>
    <%= f.number_field :avg_happy, in: 1..5, step: 0.1, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label 'What actions came out of the retrospective?' %>
    <%= f.text_field :retro_actions, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label 'Are you on target?' %><br>
    <%= f.radio_button :on_target, '1' %> 1
    <%= f.radio_button :on_target, '2' %> 2
    <%= f.radio_button :on_target, '3' %> 3
    <%= f.radio_button :on_target, '4' %> 4
    <%= f.radio_button :on_target, '5' %> 5
  </div>

  <div class="field">
    <%= f.label 'Organization helping you?' %><br>
    <%= f.radio_button :organization_helping, '1' %> 1
    <%= f.radio_button :organization_helping, '2' %> 2
    <%= f.radio_button :organization_helping, '3' %> 3
    <%= f.radio_button :organization_helping, '4' %> 4
    <%= f.radio_button :organization_helping, '5' %> 5
  </div>

  <div class="field">
    <%= f.label 'Team is able to pull this off' %><br>
    <%= f.radio_button :able_to_pull_of, '1' %> 1
    <%= f.radio_button :able_to_pull_of, '2' %> 2
    <%= f.radio_button :able_to_pull_of, '3' %> 3
    <%= f.radio_button :able_to_pull_of, '4' %> 4
    <%= f.radio_button :able_to_pull_of, '5' %> 5
  </div>

  <div class="field form-group">
    <%= f.label 'What help from management do you need?' %>
    <%= f.text_field :impediment, class:"form-control" %>
  </div>

  <%= f.hidden_field :phase_id, value: @phase.id %>

  <div class="actions">
    <%= f.submit "Start sprinting", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/sprints/_end_form.html.erb
<p><b>Project:</b> <em><%= @project.name %></em> - <b>Phase:</b> <em><%= @phase.name %></em></p>
<%= form_for([@project, @phase, @sprint]) do |f| %>
  <% if @sprint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sprint.errors.count, "error") %> prohibited this sprint from being saved:</h2>

      <ul>
      <% @sprint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'What have you done?' %>
    <%= f.text_field :things_done %>
  </div>

  <div class="field">
    <%= f.label 'Estimated sprint points' %>
    <%= f.number_field :est_points, disabled: true %>
  </div>

  <div class="field">
    <%= f.label 'Actual sprint points' %>
    <%= f.number_field :act_points  %>
  </div>

  <div class="field">
    <%= f.label 'What have you learned?' %>
    <%= f.text_field :things_learned %>
  </div>

  <% @phase.experiments.each do |exp| %>
    <h2><%= exp.name %></h2>
    <%= f.fields_for :experiments, exp do |ff| %>
    <div>
      <% if !exp.metric_1.empty? %>
        <%= ff.label exp.metric_1 %>
        <%= ff.number_field :target_succes_metric_1, disabled: true %>
        <%= ff.number_field :act_succes_metric_1 %>
      <% end %>
    </div>
    <div>
      <% if !exp.metric_2.empty? %>
        <%= ff.label exp.metric_2 %>
        <%= ff.number_field :target_succes_metric_2, disabled: true %>
        <%= ff.number_field :act_succes_metric_2 %>
      <% end %>
    </div>
    <div>
      <% if !exp.metric_3.empty? %>
        <%= ff.label exp.metric_3 %>
        <%= ff.number_field :target_succes_metric_3, disabled: true %>
        <%= ff.number_field :act_succes_metric_3 %>
      <% end %>
    </div>
    <div>
      <% if !exp.metric_4.empty? %>
        <%= ff.label exp.metric_4 %>
        <%= ff.number_field :target_succes_metric_4, disabled: true %>
        <%= ff.number_field :act_succes_metric_4 %>
      <% end %>
    </div>
    <div>
      <% if !exp.metric_5.empty? %>
        <%= ff.label exp.metric_5 %>
        <%= ff.number_field :target_succes_metric_5, disabled: true %>
        <%= ff.number_field :act_succes_metric_5 %>
      <% end %>
    </div>
    <% end %>

  <% end %>

  <%= f.hidden_field :phase_id, value: @phase.id %>
  <%= f.hidden_field :completed, value: true %>

  <div class="actions">
    <%= f.submit "End sprint and update experiment data" %>
  </div>
<% end %>

app/views/sprints/_form.html.erb
<p><b>Project:</b> <em><%= @project.name %></em> - <b>Phase:</b> <em><%= @phase.name %></em></p>
<%= form_for([@project, @phase, @sprint]) do |f| %>
  <% if @sprint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sprint.errors.count, "error") %> prohibited this sprint from being saved:</h2>

      <ul>
      <% @sprint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Select the relevant experiments for this sprint:" %>
    <%= f.collection_check_boxes :experiment_ids, @phase.experiments.all, :id, :name do |b| %>
    <div class="collection-check-box">
      <%= b.check_box %>
      <%= b.label %>
    </div>
    <% end %>
  </div>

  <div class="field form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :start_date %>
    <%= f.date_select :start_date, { ampm: true, order: [:day, :month, :year] }, { class: "form-control" } %>
  </div>

  <div class="field form-group">
    <%= f.label :end_date %>
    <%= f.date_select :end_date, { ampm: true, order: [:day, :month, :year] }, { class: "form-control" } %>
  </div>

  <div class="field form-group">
    <%= f.label 'Estimated sprint points' %>
    <%= f.number_field :est_points, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label 'Average happy score' %>
    <%= f.number_field :avg_happy, in: 1..5, step: 0.1, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label 'What actions came out of the retrospective?' %>
    <%= f.text_field :retro_actions, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label 'Are you on target?' %><br>
    <%= f.radio_button :on_target, '1' %> 1
    <%= f.radio_button :on_target, '2' %> 2
    <%= f.radio_button :on_target, '3' %> 3
    <%= f.radio_button :on_target, '4' %> 4
    <%= f.radio_button :on_target, '5' %> 5
  </div>

  <div class="field">
    <%= f.label 'Organization helping you?' %><br>
    <%= f.radio_button :organization_helping, '1' %> 1
    <%= f.radio_button :organization_helping, '2' %> 2
    <%= f.radio_button :organization_helping, '3' %> 3
    <%= f.radio_button :organization_helping, '4' %> 4
    <%= f.radio_button :organization_helping, '5' %> 5
  </div>

  <div class="field">
    <%= f.label 'Team is able to pull this off' %><br>
    <%= f.radio_button :able_to_pull_of, '1' %> 1
    <%= f.radio_button :able_to_pull_of, '2' %> 2
    <%= f.radio_button :able_to_pull_of, '3' %> 3
    <%= f.radio_button :able_to_pull_of, '4' %> 4
    <%= f.radio_button :able_to_pull_of, '5' %> 5
  </div>

  <div class="field form-group">
    <%= f.label 'What help from management do you need?' %>
    <%= f.text_field :impediment, class:"form-control" %>
  </div>

  <%= f.hidden_field :phase_id, value: @phase.id %>

  <div class="actions">
    <%= f.submit "Create Sprint", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/sprints/edit.html.erb
<h1>Editing Sprint</h1>

<%= render 'form' %>

<%= link_to 'Show', project_phase_sprint_path(@project.id, @phase.id, @sprint) %> |
<%= link_to 'List', project_phase_sprints_path(@project.id, @phase.id) %>

app/views/sprints/end_sprint.html.erb
<h1>End of sprint: <%= @sprint.name %></h1>
<br />
<%= render 'end_form' %>

<%= link_to 'Show', project_phase_sprint_path(@project.id, @phase.id, @sprint) %> |
<%= link_to 'List', project_phase_sprints_path(@project.id, @phase.id) %>

app/views/sprints/finalize.html.erb
<h1>End of sprint: <%= @sprint.name %></h1>
<br />
<%= render 'finalize_form' %>

<%= link_to 'Show', project_phase_sprint_path(@project.id, @phase.id, @sprint) %> |
<%= link_to 'List', project_phase_sprints_path(@project.id, @phase.id) %>

app/views/sprints/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sprints</h1>
<h3>Project: <%= @project.name %> - Phase: <%= @phase.name %></h3>
<br>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Completed</th>
      <th>ID</th>
    </tr>
  </thead>

  <tbody>
    <% @sprints.each do |sprint| %>
      <tr>
        <td><%= sprint.name %></td>
        <td><%= sprint.start_date %></td>
        <td><%= sprint.end_date %></td>
        <td><%= sprint.completed %></td>
        <td><%= link_to 'Show', project_phase_sprint_path(@project.id, @phase.id, sprint) %></td>
        <td><%= link_to 'Edit', edit_project_phase_sprint_path(@project.id, @phase.id, sprint) %></td>
        <td><%= link_to 'Destroy', project_phase_sprint_path(@project.id, @phase.id, sprint), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sprint', new_project_phase_sprint_path(@project.id, @phase.id) %>

app/views/sprints/new.html.erb
<h1>New Sprint</h1>

<%= render 'form' %>

<%= link_to 'List', project_phase_sprints_path(@project.id, @phase.id) %>

app/views/sprints/show.html.erb
<p id="notice"><%= notice %></p>

<p><b>Project:</b> <em><%= @project.name %></em> - <b>Phase:</b> <em><%= @phase.name %></em></p>

<p>
  <strong>Name:</strong>
  <%= @sprint.name %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @sprint.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @sprint.end_date %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @sprint.completed == false ? 'Not yet' : 'Done'%>
</p>

<p>
  <strong>Estimated sprint points:</strong>
  <%= @sprint.est_points %>
</p>

<p>
  <strong>Average happy score:</strong>
  <%= @sprint.avg_happy %>
</p>

<p>
  <strong>What actions came out of the retrospective?</strong>
  <%= @sprint.retro_actions %>
</p>

<p>
  <strong>Are you on target?</strong>
  <%= @sprint.on_target %>
</p>

<p>
  <strong>Organization helping you?</strong>
  <%= @sprint.organization_helping %>
</p>

<p>
  <strong>Team is able to pull this off?</strong>
  <%= @sprint.able_to_pull_of %>
</p>

<p>
  <strong>What help from management do you need?</strong>
  <%= @sprint.impediment %>
</p>

<%= link_to 'Edit', edit_project_phase_sprint_path(@project.id, @phase.id, @sprint) %> |
<%= link_to 'List', project_phase_sprints_path(@project.id, @phase.id) %>

app/views/sprints/start_sprint.html.erb
<h1>Start of sprint: <%= @sprint.id %></h1>
<br />
<%= render 'begin_form' %>

<%= link_to 'Show', project_phase_sprint_path(@project.id, @phase.id, @sprint) %> |
<%= link_to 'List', project_phase_sprints_path(@project.id, @phase.id) %>