config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get '/projects/:project_id/phases/:phase_id/sprints/:id/start_sprint' => 'sprints#start_sprint', as: :sprint_start
  get '/projects/:project_id/phases/:phase_id/sprints/:id/end_sprint' => 'sprints#end_sprint', as: :sprint_end

  resources :projects do
    resources :team_members
    resources :teams
    resources :phases do
      resources :experiments
      resources :sprints
    end
  end

  root 'projects#index'

  post 'send_weekly_emails' => 'projects#send_weekly_emails', as: :email_sent

end

app/models/project.rb
class Project < ApplicationRecord
  has_many :teams, through: :phases
  has_many :team_members, through: :teams
  has_many :phases, inverse_of: :project
  belongs_to :user
  accepts_nested_attributes_for :phases, allow_destroy: true, :reject_if => :all_blank

  STAGES = ['Explore', 'Experiment', 'Grow', 'Scale']

  def self.get_list_of_phases
    list_of_phases = []
    STAGES.each_with_index do |stage, index|
      list_of_phases << [stage, index]
    end
    list_of_phases
  end

  def current_phase
    Phase.find(self.current_stage_id)
  end

  def get_list_of_project_phases
    ret_array = []
    self.phases.each do |p|
      ret_array << [p.name, p.id]
    end
    ret_array
  end

  def set_stage
    if !earliest_uncompleted.nil?
      self.update(current_stage_id:earliest_uncompleted.id)
    elsif !last_completed.nil?
      self.update(current_stage_id:last_completed.id)
    else
      id = self.phases.last.id
      self.update(current_stage_id: id)
    end
  end

  def get_mailer_for_current_phase
    current_phase = Phase.find(self.current_stage_id)
    users = current_phase.team.users
    sprints = []
    current_phase.sprints.each do |sprint|
      today = Date.today
      if (sprint.end_date >= today) && (sprint.end_date <= (today + 7))
        sprints << sprint
      end
    end
    {users: users, sprints:sprints}
  end

  def define_next_sequence
    # existing_sequences = self.phases.map{|x| x[:sequence]}
    # if existing_sequences.length > 0
    #   existing_sequences = existing_sequences.sort
    #   new_sequence = existing_sequences[-1]
    #   new_sequence += 1
    # else
    #   # else as fallback, normally phase is always present after project creation
    #   new_sequence = 0
    # end
    # new_sequence

    existing_sequences = self.phases.map{|x| x[:sequence]}
    highest_sequence = existing_sequences.max
    if existing_sequences.empty?
      0
    elsif highest_sequence >= STAGES.length - 1
      nil
    else
      highest_sequence + 1
    end

  end

  def role_check(user)
    self.user == user || self.portfoliomanager_id == user.id || self.coach_id == user.id
  end



  def earliest_uncompleted
    self.phases.where(:completed => false).sort{ |a,b| a.sequence <=> b.sequence }.first
  end

  def last_completed
    self.phases.where(:completed => true).sort{ |a,b| a.sequence <=> b.sequence }.last
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter
  load_and_authorize_resource
  include SprintEmail # method "run_mailer(project)" is now available for project

  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def send_weekly_emails
    project_id = params[:project_id]
    project = Project.find(project_id)
    run_mailer(project)
  end

  # GET /projects
  # GET /projects.json
  def index
    if user_signed_in?
    @projects = Project.all
    else
    redirect_to new_user_session_path
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    @project.phases.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user = current_user
    respond_to do |format|
      if @project.save
        format.html { redirect_to edit_project_phase_path(project_id: @project.id, id: @project.phases.last) }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :active, :user_id, :portfoliomanager_id, :coach_id, phases_attributes: [:id,:sequence])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper

end

app/views/projects/_form.html.erb
<div class="container">
  <%= form_for(project) do |f| %>
    <% if project.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

        <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class:"form-control" %>
    </div>

    <div class="field form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class:"form-control"%>
    </div>

    <div class="field form_group">
      <%= f.label :portfoliomanager_id %>
      <%= f.collection_select(:portfoliomanager_id, User.where(role: 'portfoliomanager'), :id, :first_name, {}, class: "form-control") %>
    </div>

    <div class="field form_group">
      <%= f.label :coach_id %>
      <%= f.collection_select(:coach_id, User.where(role: 'coach'), :id, :first_name, {}, class: "form-control") %>
    </div>

    <%= f.hidden_field :active, :value => TRUE %>

    <% if project.new_record? %>
      <%= f.fields_for :phases do |m| %>
       <div class="field form-group">
         <%= m.label 'Current phase' %>
         <%= m.select :sequence, Project.get_list_of_phases, {}, class: "form-control" %>
       </div>
      <% end %>
    <% end %>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'List', projects_path %>

app/views/projects/index.html.erb
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css">

<p id="notice"><%= notice %></p>

<h3>Active Projects</h3>


<div class="container block">
    <% @projects.each do |project| %>
    <% if project.active && project.role_check(current_user) %>
    <div class="col-md-3 col-sm-6">
        <%= link_to project do %>
        <% target = project.phases.find(project.current_stage_id).sprints.where(:completed => FALSE).first&.on_target || "-" %>
        <% happy = project.phases.find(project.current_stage_id).sprints.where(:completed => FALSE).first&.avg_happy || "-" %>
        <% organization = project.phases.find(project.current_stage_id).sprints.where(:completed => FALSE).first&.organization_helping || "-" %>
        <% pullof = project.phases.find(project.current_stage_id).sprints.where(:completed => FALSE).first&.able_to_pull_of || "-" %>
        <div class="panel panel-default activeblock">
            <div class="panel-body" style="height: 130px">

                <div style="width: 50%; float:left">
                    <p class="projectname"><%= project.name %></p>
                    <span class="happiness">
                      <%= happy %>
                    </span>
                    <p class="meters">Happiness rating</p>
                </div>

                <div style="width: 50%; float:right">
                    <p class="meters">On target</p>
                    <div class="progress_bar" value="<%= target * 20 || "-" %>">
                        <div class="progress-label">Loading...</div>
                    </div>
                    <p class="meters">Governance</p>
                    <div class="progress_bar" value="<%= organization * 20 || "-" %>">
                        <div class="progress-label">Loading...</div>
                    </div>
                    <p class="meters">Team</p>
                    <div class="progress_bar" value="<%= pullof * 20 || "-" %>">
                        <div class="progress-label">Loading...</div>
                    </div>
                </div>
            </div>
            <% end %>
        </div>
    </div>
    <% end %>
    <% end %>
    <div class="col-md-3 col-sm-6 text-center">
      <% if can? :manage, Project %>
        <%= link_to new_project_path do %>
          <div class="panel panel-default">
              <div class="panel-body" style="height: 130px">
                  <td>Create a new project..</td>
              </div>
          </div>
        <% end %>
      <%end%>
    </div>


</div>

<br><br><br>
<h3>Past Projects</h3>

<div class="container block">
    <% @projects.each do |project| %>
    <% if project.active == false && project.role_check(current_user) %>
    <div class="col-md-3 col-sm-6">
        <%= link_to project do %>
        <div class="panel panel-default">
            <div class="panel-body" style="height: 80px">
                <td><%= project.name %></td><br>
            </div>
            <% end %>
        </div>
    </div>
    <% end %>
    <% end %>
</div>

<script>

$( document ).ready(function() {



$(function() {
  $('.progress_bar').each(function() {
var progressbar = $(this),
      progressLabel = $(this).find( ".progress-label" ),
    progressvalue = $(this).attr('value');
console.log(progressvalue);

    progressbar.progressbar({
      value: false,
      change: function() {

        progressLabel.text( progressbar.progressbar( "value" )  );
      },
      complete: function() {
        progressLabel.text( "So happy!" );
      }
    });

    function progress() {

      var val = progressbar.progressbar( "value" ) || 0;

      progressbar.progressbar( "value", val + 1 )
        .removeClass("beginning middle end")
        .addClass(val < 40 ? "beginning" : val < 80 ? "middle" : "end");


      if ( val < progressvalue ) {
        setTimeout( progress, 1 );
      }
    }

    setTimeout( progress, 1 );
       });
    });

    });

    </script>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'List', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Active:</strong>
  <%= @project.active %>
</p>

<div class="phase_overview">
  <table class="phase_table">
    <tr class="top_row">
      <th>Current</th>
      <th>Phase</th>
      <th>Start date</th>
      <th>End date</th>
    </tr>
    <% @project.phases.order(:sequence).each do |phase| %>
      <tr>
        <td>
        <% if @project.current_stage_id == phase.id %>
          <span class="glyphicon glyphicon-check boxes"></span>
        <% else %>
          <span class="glyphicon glyphicon-unchecked boxes"></span>
        <% end %>
      </td>
        <td><%= link_to phase.name, project_phase_path(@project.id, phase) %></td>
        <td><%= phase.start_date.strftime("%d %B %Y") %></td>
        <td><%= phase.end_date.strftime("%d %B %Y") %></td>
      </tr>
    <% end %>
  </table>
  <br>
  <%= link_to 'New phase', new_project_phase_path(@project.id), :class => 'btn btn-large btn-success' %>
</div>

<% if can? :update, @project %>
  <%= link_to 'Edit project', edit_project_path(@project) %>
<% end %>
<% if can? :destroy, @project %>
  <%= link_to 'Destroy', @project, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
<%= link_to 'List', projects_path %>