config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get '/projects/:project_id/phases/:phase_id/sprints/:id/start_sprint' => 'sprints#start_sprint', as: :sprint_start
  get '/projects/:project_id/phases/:phase_id/sprints/:id/end_sprint' => 'sprints#end_sprint', as: :sprint_end

  resources :projects do
    resources :team_members
    resources :teams
    resources :phases do
      resources :experiments
      resources :sprints
    end
  end

  root 'projects#index'

  post 'send_weekly_emails' => 'projects#send_weekly_emails', as: :email_sent

end

app/controllers/phases_controller.rb
class PhasesController < ApplicationController
  before_action :set_project, only: [:index, :show, :new, :edit, :create, :update, :destroy]
  before_action :set_phase, only: [:show, :edit, :update, :destroy]

  # GET /phases
  # GET /phases.json
  def index
    @phases = Phase.where(project_id: params[:project_id])
  end

  # GET /phases/1
  # GET /phases/1.json
  def show
    @team = @phase.team
  end

  # GET /phases/new
  def new
    sequence = @project.phases.order(:sequence).last[:sequence]
    if sequence == (Project::STAGES.length - 1)
      redirect_to project_path(@project.id), notice: 'New phase cannot be created'
    else
      @phase = Phase.new(sequence: sequence + 1)
    end
  end

  # GET /phases/1/edit
  def edit

  end

  # POST /phases
  # POST /phases.json
  def create
    @phase = Phase.new(phase_params)

    respond_to do |format|
      if @phase.save
        format.html { redirect_to project_phase_path(@project.id, @phase), notice: 'Phase was successfully created.' }
        format.json { render :show, status: :created, location: @phase }
      else
        format.html { render :new }
        format.json { render json: @phase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phases/1
  # PATCH/PUT /phases/1.json
  def update
    respond_to do |format|
      if @phase.update(phase_params)
        format.html
        format.json { render :nothing => true }
      else
        format.html { render :edit }
        format.json { render json: @phase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phases/1
  # DELETE /phases/1.json
  def destroy
    @phase.destroy
    respond_to do |format|
      format.html { redirect_to project_phases_path(@project.id), notice: 'Phase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:project_id])
    end
    def set_phase
      @phase = Phase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phase_params
      params.require(:phase).permit(:project_id, :start_date, :end_date, :interval, :sequence, :long_term_vision, :kpi_s, :criteria, :bottlenecks, :problem_definition, :solutions, :long_term, :key_benefits, :vision, :test_first, :sprint_amount, :proof_of_value, :background, :note)
    end
end

app/helpers/phases_helper.rb
module PhasesHelper
end

app/views/phases/_form.html.erb
<h3>Project: <em><%= @project.name %></em> - Phase: <em><%= @phase.name %></em></h3>

<%= form_for([@project, @phase]) do |f| %>

  <% if @phase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phase.errors.count, "error") %> prohibited this phase from being saved:</h2>

      <ul>
      <% @phase.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="container">
  <hr>
      <div class="panel-group" id="accordion">

        <div class="panel panel-default">
            <div class="panel-heading">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseSixteen">
                    <h4 class="panel-title">
                        <%= f.label :background %>
                    </h4>
                </a>
            </div>
            <div id="collapseSixteen" class="panel-collapse collapse">
                <div class="panel-body">
                    <%= f.text_area :background, class:"form-control" %>
                </div>
            </div>
        </div>



          <div class="panel panel-default">
              <div class="panel-heading">
                  <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseFive">
                      <h4 class="panel-title">
                          <%= f.label :long_term_vision %>
                      </h4>
                  </a>
              </div>
              <div id="collapseFive" class="panel-collapse collapse">
                  <div class="panel-body">
                      <%= f.text_area :long_term_vision, class:"form-control" %>
                  </div>
              </div>
          </div>

          <div class="panel panel-default">
              <div class="panel-heading">
                  <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseSix">
                      <h4 class="panel-title">
                          <%= f.label :kpi_s %>
                      </h4>
                  </a>
              </div>
              <div id="collapseSix" class="panel-collapse collapse">
                  <div class="panel-body">
                      <%= f.text_area :kpi_s, class:"form-control" %>
                  </div>
              </div>
          </div>

          <div class="panel panel-default">
              <div class="panel-heading">
                  <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseSeven">
                      <h4 class="panel-title">
                          <%= f.label :criteria %>
                      </h4>
                  </a>
              </div>
              <div id="collapseSeven" class="panel-collapse collapse">
                  <div class="panel-body">
                      <%= f.text_area :criteria, class:"form-control" %>
                  </div>
              </div>
          </div>

          <div class="panel panel-default">
              <div class="panel-heading">
                  <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseEight">
                      <h4 class="panel-title">
                          <%= f.label :bottlenecks %>
                      </h4>
                  </a>
              </div>
              <div id="collapseEight" class="panel-collapse collapse">
                  <div class="panel-body">
                      <%= f.text_area :bottlenecks, class:"form-control" %>
                  </div>
              </div>
          </div>

          <div class="panel panel-default">
              <div class="panel-heading">
                  <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseNine">
                      <h4 class="panel-title">
                          <%= f.label :problem_definition %>
                      </h4>
                  </a>
              </div>
              <div id="collapseNine" class="panel-collapse collapse">
                  <div class="panel-body">
                      <%= f.text_area :problem_definition, class:"form-control" %>
                  </div>
              </div>
          </div>

          <div class="panel panel-default">
              <div class="panel-heading">
                  <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseTen">
                      <h4 class="panel-title">
                          <%= f.label :solutions %>
                      </h4>
                  </a>
              </div>
              <div id="collapseTen" class="panel-collapse collapse">
                  <div class="panel-body">
                      <%= f.text_area :solutions, class:"form-control" %>
                  </div>
              </div>
          </div>

          <div class="panel panel-default">
              <div class="panel-heading">
                  <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseEleven">
                      <h4 class="panel-title">
                          <%= f.label :long_term %>
                      </h4>
                  </a>
              </div>
              <div id="collapseEleven" class="panel-collapse collapse">
                  <div class="panel-body">
                      <%= f.text_area :long_term, class:"form-control" %>
                  </div>
              </div>
          </div>

          <div class="panel panel-default">
              <div class="panel-heading">
                  <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseTwelve">
                      <h4 class="panel-title">
                          <%= f.label :key_benefits %>
                      </h4>
                  </a>
              </div>
              <div id="collapseTwelve" class="panel-collapse collapse">
                  <div class="panel-body">
                      <%= f.text_area :key_benefits, class:"form-control" %>
                  </div>
              </div>
          </div>

          <div class="panel panel-default">
              <div class="panel-heading">
                  <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseThirteen">
                      <h4 class="panel-title">
                          <%= f.label :vision %>
                      </h4>
                  </a>
              </div>
              <div id="collapseThirteen" class="panel-collapse collapse">
                  <div class="panel-body">
                      <%= f.text_area :vision, class:"form-control" %>
                  </div>
              </div>
          </div>

          <div class="panel panel-default">
              <div class="panel-heading">
                  <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseFourteen">
                      <h4 class="panel-title">
                          <%= f.label :test_first %>
                      </h4>
                  </a>
              </div>
              <div id="collapseFourteen" class="panel-collapse collapse">
                  <div class="panel-body">
                      <%= f.text_area :test_first, class:"form-control" %>
                  </div>
              </div>
          </div>

          <div class="panel panel-default">
              <div class="panel-heading">
                  <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseFifteen">
                      <h4 class="panel-title">
                          <%= f.label 'Project goal' %>
                      </h4>
                  </a>
              </div>
              <div id="collapseFifteen" class="panel-collapse collapse">
                  <div class="panel-body">
                      <%= f.text_area :proof_of_value, class:"form-control", placeholder: "" %>
                  </div>
              </div>
          </div>
          <div class="panel panel-default">
              <div class="panel-heading">
                  <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseSeventeen">
                      <h4 class="panel-title">
                          <%= f.label :note %>
                      </h4>
                  </a>
              </div>
              <div id="collapseSeventeen" class="panel-collapse collapse">
                  <div class="panel-body">
                      <%= f.text_area :note, class:"form-control" %>
                  </div>
              </div>
          </div>
          <div class="panel panel-default">
              <div class="panel-heading">
                  <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                      <h4 class="panel-title">
                          <%= f.label :start_date %>
                      </h4>
                  </a>
              </div>
              <div id="collapseOne" class="panel-collapse collapse in">
                  <div class="panel-body">
                      <%= f.datetime_select :start_date, { ampm: true, order: [:day, :month, :year] }, { class: "form-control" } %>
                  </div>
              </div>
            </div>
              <div class="panel panel-default">
                  <div class="panel-heading">
                      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseEightteen">
                          <h4 class="panel-title">
                              <%= f.label 'How many sprints will you do?'  %>
                          </h4>
                      </a>
                  </div>
                  <div id="collapseEightteen" class="panel-collapse collapse">
                      <div class="panel-body">
                          <%= f.text_area :sprint_amount, class:"form-control" %>
                      </div>
                  </div>
              </div>
              <div class="panel panel-default">
                  <div class="panel-heading">
                      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                          <h4 class="panel-title">
                              <%= f.label 'How long is the sprint?'%>
                          </h4>
                      </a>
                  </div>
                  <div id="collapseThree" class="panel-collapse collapse">
                      <div class="panel-body">
                          <%= f.select :interval, [["1 week", 1] ,["2 weeks", 2], ["3 weeks", 3],["4 weeks", 4]], {}, class: "form-control" %>
                      </div>
                  </div>
              </div>
          </div>
      </div>
      
    <%= f.hidden_field :completed, :value => FALSE %>
    <%= f.hidden_field :project_id, value: @project.id %>
    <%= f.hidden_field :sequence, value: @phase.sequence %>

    <div class="actions">
      <%= f.submit "Create Phase", class: "btn-primary"%>
    </div>
</div>
<% end %>

<script>


$('input, select, textarea').change(function () {
    if ($(this).val() < 1 ) {
        $(this).parentsUntil(".panel-default").siblings(".panel-heading").removeClass('completed');
    }
    else if ($(this).val().length >= 1) {
        $(this).parentsUntil(".panel-default").siblings(".panel-heading").addClass('completed');
    }
});


</script>

app/views/phases/edit.html.erb
<h1>Editing Phase: <%= @phase.name %></h1>

<%= render 'formedit' %>

<%= link_to 'Show', project_phase_path(@project.id, @phase) %> |
<%= link_to 'List', project_phases_path(@project.id) %>

app/views/phases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Phases for <%= @project.name %></h1>
<br>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Interval</th>
      <th>Long term vision</th>
      <th>Kpi s</th>
      <th>Criteria</th>
      <th>Bottlenecks</th>
      <th>Problem definition</th>
      <th>Solutions</th>
      <th>Long term</th>
      <th>Key benefits</th>
      <th>Vision</th>
      <th>Test first</th>
      <th>Proof of value</th>
      <th>Background</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @phases.each do |phase| %>
      <tr>
        <td><%= phase.name %></td>
        <td><%= phase.start_date %></td>
        <td><%= phase.end_date %></td>
        <td><%= phase.interval %> weeks</td>
        <td><%= phase.long_term_vision %></td>
        <td><%= phase.kpi_s %></td>
        <td><%= phase.criteria %></td>
        <td><%= phase.bottlenecks %></td>
        <td><%= phase.problem_definition %></td>
        <td><%= phase.solutions %></td>
        <td><%= phase.long_term %></td>
        <td><%= phase.key_benefits %></td>
        <td><%= phase.vision %></td>
        <td><%= phase.test_first %></td>
        <td><%= phase.proof_of_value %></td>
        <td><%= phase.background %></td>
        <td><%= phase.note %></td>
        <td><%= link_to 'Show', project_phase_path(@project.id, phase) %></td>
        <td><%= link_to 'Edit', edit_project_phase_path(@project.id, phase) %></td>
        <td><%= link_to 'Destroy', project_phase_path(@project.id, phase), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New phase', new_project_phase_path(@project.id), class: "btn btn-large btn-success" %>

app/views/phases/new.html.erb
<h1>New Phase</h1>

<%= render 'form'%>

<%= link_to 'List', project_phases_path(@project.id) %>

app/views/phases/show.html.erb
<% content_for :head do %>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
   <script src="//code.jquery.com/jquery-1.10.2.js"></script>
   <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
 <% end %>

<p id="notice"><%= notice %></p>

<p><b>Project:</b> <em><%= @project.name %></em>

<h1>
  Phase: <%= @phase.name %>
</h1>

<hr>


<div class="container">
  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#menu1">Dash</a></li>
    <li><a data-toggle="tab" href="#menu2">Phase</a></li>
  </ul>

  <div class="tab-content">
    <div id="menu1" class="tab-pane fade in active">
      <br>
      <div class="phase_overview">
        <table class="phase_table">
          <tr class="top_row">
            <th>Completed</th>
            <th colspan="2">Experiment</th>
            <th>Start date</th>
            <th>End date</th>
          <% @phase.experiments.order(:start_date).each do |experiment| %>
            <tr>
              <td>
              <% if experiment.completed %>
                <span class="glyphicon glyphicon-check boxes"></span>
              <% else %>
                <span class="glyphicon glyphicon-unchecked boxes"></span>
              <% end %>
              </td>
              <td colspan="2"><strong><%= link_to experiment.name, project_phase_experiment_path(@project.id, @phase.id, experiment) %></strong></td>
              <td><%= experiment.start_date.strftime("%d %B %Y") %></td>
              <td><%= experiment.end_date.strftime("%d %B %Y") %></td>
            </tr>
            <tr>
              <td><%= experiment.metric_1 %></td>
              <td><%= experiment.metric_2 %></td>
              <td><%= experiment.metric_3 %></td>
              <td><%= experiment.metric_4 %></td>
              <td><%= experiment.metric_5 %></td>
            </tr>
            <tr>
              <td><%= experiment.ratio_completion_1[:number] %>
              <p><progress id="p" value=<%= experiment.ratio_completion_1[:ratio] * 100 %> max=100><span></span>%</progress></p></td>
              <td><%= experiment.ratio_completion_2[:number] %>
              <p><progress id="p" value=<%= experiment.ratio_completion_2[:ratio] * 100 %> max=100><span></span>%</progress></p></td>
              <td><%= experiment.ratio_completion_3[:number] %>
              <p><progress id="p" value=<%= experiment.ratio_completion_3[:ratio] * 100 %> max=100><span></span>%</progress></p></td>
              <td><%= experiment.ratio_completion_4[:number] %>
              <p><progress id="p" value=<%= experiment.ratio_completion_4[:ratio] * 100 %> max=100><span></span>%</progress></p></td>
              <td><%= experiment.ratio_completion_5[:number] %>
              <p><progress id="p" value=<%= experiment.ratio_completion_5[:ratio] * 100 %> max=100><span></span>%</progress></p></td>
            </tr>
            <tr >
              <td colspan="5"></td>
            </tr>
          <% end %>
        </table>

        <br>
        <%= link_to('Create new experiment', new_project_phase_experiment_path(@project.id, @phase.id), :class => 'btn btn-large btn-success')  %>
      </div>

      <hr>

      <div class="phase_overview">
        <table class="phase_table">
          <tr class="top_row">
            <th>Completed</th>
            <th>Sprint</th>
            <th>Start date</th>
            <th>End date</th>
            <th>Story points</th>
            <th>Happiness</th>
            <th colspan="2"></th>
          </tr>
          <% @phase.sprints.order(:start_date).each do |sprint| %>
            <tr>
              <td>
              <% if sprint.completed %>
                <span class="glyphicon glyphicon-check boxes"></span>
              <% else %>
                <span class="glyphicon glyphicon-unchecked boxes"></span>
              <% end %>
            </td>
              <td><%= "sprint #{@phase.sprints.find_index(sprint) + 1}" %></td>
              <td><%= sprint.start_date.strftime("%d %B %Y") %></td>
              <td><%= sprint.end_date.strftime("%d %B %Y") %></td>
              <td> </td>
              <td> </td>
              <% if !sprint.completed %>
                <td><%= link_to "Start", sprint_start_path(@project.id, @phase.id, sprint.id) %></td>
                <td><%= link_to "End", sprint_end_path(@project.id, @phase.id, sprint.id) %></td>
              <% else %>
                <td colspan="2">Sprint completed</td>
              <% end %>
              <td> </td>
            </tr>
          <% end %>
        </table>
        <br>
      </div>

        <%= link_to('Team', project_team_path(@team.project @team), :class => 'btn btn-large btn-success')  %>
    </div>
    <div id="menu2" class="tab-pane fade">
      <br>
      <p>
        <strong>Start date:</strong>
        <%= @phase.start_date %>
      </p>

      <p>
        <strong>End date:</strong>
        <%= @phase.end_date %>
      </p>

      <p>
        <strong>Interval:</strong>
        <%= @phase.interval %>
      </p>

      <!-- <p>
        <strong>Sequence:</strong>
        <%= @phase.sequence %>
      </p> -->

      <p>
        <strong>Long term vision:</strong>
        <%= @phase.long_term_vision %>
      </p>

      <p>
        <strong>Kpi s:</strong>
        <%= @phase.kpi_s %>
      </p>

      <p>
        <strong>Criteria:</strong>
        <%= @phase.criteria %>
      </p>

      <p>
        <strong>Bottlenecks:</strong>
        <%= @phase.bottlenecks %>
      </p>

      <p>
        <strong>Problem definition:</strong>
        <%= @phase.problem_definition %>
      </p>

      <p>
        <strong>Solutions:</strong>
        <%= @phase.solutions %>
      </p>

      <p>
        <strong>Long term:</strong>
        <%= @phase.long_term %>
      </p>

      <p>
        <strong>Key benefits:</strong>
        <%= @phase.key_benefits %>
      </p>

      <p>
        <strong>Vision:</strong>
        <%= @phase.vision %>
      </p>

      <p>
        <strong>Test first:</strong>
        <%= @phase.test_first %>
      </p>

      <p>
        <strong>Proof of value:</strong>
        <%= @phase.proof_of_value %>
      </p>

      <p>
        <strong>Background:</strong>
        <%= @phase.background %>
      </p>

      <p>
        <strong>Note:</strong>
        <%= @phase.note %>
      </p>

      <br>
      <%= link_to 'Edit', edit_project_phase_path(@phase.project, @phase) %> |
      <%= link_to 'List', project_phases_path(@phase.project) %>

    </div>

  </div>
</div>