config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get '/projects/:project_id/phases/:phase_id/sprints/:id/start_sprint' => 'sprints#start_sprint', as: :sprint_start
  get '/projects/:project_id/phases/:phase_id/sprints/:id/end_sprint' => 'sprints#end_sprint', as: :sprint_end

  resources :projects do
    resources :team_members
    resources :teams
    resources :phases do
      resources :experiments
      resources :sprints
    end
  end

  root 'projects#index'

  post 'send_weekly_emails' => 'projects#send_weekly_emails', as: :email_sent

end

app/views/layouts/_header.html.erb
<link rel="stylesheet" href="/assets/navheader.scss">

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("tacho_logo.png", :border=>0, :class => 'navbar-brand') + "", "/"%></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
        <li><%= link_to "Projects", projects_path , :class => "btn btn-info darkblue" %></li>
    </ul>

    <div class="input-group navbar-form navbar-left">
        <%= form_tag(new_project_path, :method => "get", id: "srch-term", class: 'navbar-form navbar-left') do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search", class: 'form-control lightblue' %>
        <span class="input-group-btn">
            <%= button_tag(type: "submit", class: 'btn btn-default darkblue') do %>
             <i class="glyphicon glyphicon-search"></i>
            <% end %>
        </span>
        <% end %>
    </div>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to  new_project_path , :class => "btn btn-info darkblue" do%>
             <i class="glyphicon glyphicon-plus"></i>
          <% end %>
        </li>

        <% if !user_signed_in? %>
            <li><%= link_to "Log In", new_user_session_path %></li>
        <% else %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.first_name %> <%= current_user.last_name %><span class="caret"></span></a>
          <ul class="dropdown-menu">
          <li><%=link_to "Edit profile", edit_user_registration_path%></li>
          <% if current_user.role == "coach" %>
          <li> <%=link_to "Admin", rails_admin_path%></li>
          <% end %>
          </ul>
          <li><%=link_to "Log Out", destroy_user_session_path, :method => :delete %></li>
      <% end %>

        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tachometer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :head %>
  </head>

  <body>
    <%= render "layouts/header" %>

<main class="container">
   <%= yield %>
</main>

  </body>
</html>